/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yhjlbisbtilayjweuifl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloamxiaXNidGlsYXlqd2V1aWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzMTc3ODQsImV4cCI6MjA4NTg5Mzc4NH0.CWT9UKyhqr8GHUBEamkKOlgFsm7D-N-sQGd4xGYSq1A"